AnotherAuctionSite/urls.py
from django.contrib import admin
from django.urls import path, include

from auctionApp.account_management import EditUser, AddUser, ChangeCurrency
from auctionApp.auction_add import AddAuction
from auctionApp.auction_bid import BidAuction
from auctionApp.auction_edit import EditAuction
from auctionApp.auctions_browse import BrowseAuctions
from auctionApp.login import Login, Logout
from auctionApp.search import Search
from auctionApp.views import home, BanAuction, ListBanned

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', home,),
    path('home/', home, name = 'home'),
    path('auctions/', BrowseAuctions.as_view(), name='auctions'),
    path('auctions/<int:number>', BrowseAuctions.fetch_auction, name='auctionFetch'),
    path('auctions/add/', AddAuction.as_view(), name='auctionAdd'),
    path('auctions/edit/', BrowseAuctions.as_view(), name='auctionEdit'),
    path('auctions/edit/<slug:query>', EditAuction.as_view(), name='auctionEdit'),
    path('auctions/bid/', BidAuction.as_view(), name='auctionBid'),
    path('auctions/bid/<int:number>', BidAuction.as_view(), name='auctionBid'),
    path('search/', Search.as_view(), name='search'),
    path('search/<slug:query>', Search.as_view, name='search'),
    path('signup/', AddUser.as_view(), name='signup'),
    path('edit_account/', EditUser.as_view(), name='edit_account'),
    path('change_currency/', ChangeCurrency.as_view(), name='change_currency'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('admin_task/', BanAuction.as_view(), name='ban_auction'),
    path('admin_task/ban/<int:number>', BanAuction.as_view(), name='auctionBan'),
    path('admin_task/list_banned/', ListBanned.as_view(), name='auctionListBanned'),

    path('api/', include('restAPI.urls')),
]

restAPI/urls.py
from django.urls import path, include
from restAPI import views

urlpatterns = [
    path('auctions/', views.auction_list),
    path('auctions/<int:number>', views.auction_detail),
    path('auctions/search=<slug:query>', views.auction_search),
]

auctionApp/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class UserSettings(models.Model):
    id = models.IntegerField(primary_key=True, unique=True)
    currency = models.CharField(max_length=3, null=True, blank=True)



class Auction(models.Model):
    seller_id = models.IntegerField()
    seller_name = models.CharField(max_length=20)
    seller_email = models.EmailField()
    title = models.CharField(max_length=100, null=False, blank=False)
    description = models.TextField(null=False, blank=False)
    starting_price = models.FloatField()
    current_price = models.FloatField()
    current_winner_id = models.IntegerField(null=True, blank=True)
    current_winner_name = models.CharField(max_length=20, default='No bids yet.')
    time_posted = models.DateTimeField()
    time_closing = models.DateTimeField()
    hash_id = models.CharField(max_length=256)
    active = models.BooleanField(default=True)
    banned = models.BooleanField(default=False)
    resolved = models.BooleanField(default=False)

    def get(self, instance):
        return self.serializable_value(instance)

    def __str__(self):
        return self.title


class Bid(models.Model):
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE)
    user_id = models.IntegerField(unique=False)
    name = models.CharField(max_length=20)
    email = models.EmailField()
    price = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __get__(self, instance, owner):
        return self.serializable_value(instance)

    def __str__(self):
        return self.timestamp.strftime('%X') + ' User ' + str(self.name) + ' on auction ' + str(self.auction) + ' (' + str(self.price) + ')'


class ExchangeRate(models.Model):
     code = models.CharField(primary_key=True, max_length=3)
     rate = models.FloatField()
     last_updated = models.DateTimeField(auto_now=True)

templates/add_auction.html
{% extends 'base.html' %}

{% block content %}
    <script>
        function updateCur(){
            var input = document.getElementById("starting_price")
            var output = document.getElementById("converted");
            output.innerHTML = (input.value * {{ rate }}).toFixed(2)
        }
    </script>

    <form action="{% url 'auctionAdd' %}" method="POST">
        {% csrf_token %}
        {% if "date" in error.values %}<span style="color: red; ">Errors in form, please fix items marked with red.</span>{% endif %}<br><br>
        <table border="0">
            <tr>
                <td>{{ form.title.label_tag }}</td>
                <td>{{ form.title }}</td>
            </tr>
            <tr>
                <td>{{ form.description.label_tag }}</td>
                <td>{{ form.description }}</td>
            </tr>
            <tr>
                <td>{{ form.starting_price.label_tag }}</td>
                <td>
                    <input type="text" name="starting_price" id="starting_price" value="0" oninput="updateCur()">
                    {% if request.session.currency != 'EUR' %}
                        = <h id="converted"> 0 </h> {{ request.session.currency }}
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td>
                    {% if "date" in error.values %}<span style="color: red; ">{% endif %}
                    End date:
                    {% if "date" in error.values %}</span>{% endif %}
                </td>
                <td>
                    <input type="datetime-local" id="end_datetime"
                           name="end_datetime" value="{{ min_date }}"
                           min="{{ min_date }}" max="{{ max_date }}" />
                    {{ form.date }}
                </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <input type="submit" value="Add" style="width: 100%">
                </td>
            </tr>
        </table>
    </form>
{% endblock %}

templates/auction_table.html
<table class="auction_item">
    <tr>
        <td>
            Title
        </td>
        <td>
            {{ auction.title }}
        </td>
    </tr>
    <tr>
        <td>
            Seller
        </td>
        <td>
            {{ auction.seller_name }}
        </td>
    </tr>
    <tr>
        <td valign="top">
            Item description
        </td>
        <td>
            <pre>{{ auction.description }}</pre>
        </td>
    </tr>
    <tr>
        <td>
            Starting price
        </td>
        <td>
            {{ starting_price }}
        </td>
    </tr>
    <tr>
        <td>
            Number of bids
        </td>
        <td>
            {{ auction.bid_set.count }}
        </td>
    </tr>
    <tr>
        <td>
            Current price
        </td>
        <td>
            {{ current_price }}
        </td>
    </tr>
    <tr>
        <td>
            Highest bid by
        </td>
        <td>
            {{ auction.current_winner_name }}
        </td>
    </tr>
    <tr>
        <td>
            Auction closing time
        </td>
        <td>
            {% if auction_time_closing %}
                {{ auction_time_closing }}
            {% else %}
                {{ auction.time_closing }}
            {% endif %}
        </td>
    </tr>
    <tr>
        <td>
            Posted on
        </td>
        <td>
            {% if auction_time_posted %}
                {{ auction_time_posted }}
            {% else %}
                {{ auction.time_posted }}
            {% endif %}
        </td>
    </tr>
</table>

templates/base.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        {% include 'static/styles.css' %}
    </style>
    <title>
        {% if page_name %}
            {{ page_name }}
        {% else %}
            Awesome auctions!
        {% endif %}
    </title>
</head>

<body>
{% include "navigation.html" %}
{% include "top.html" %}

<div class="content">
{{ global.session.currency }}
    {% if info_message %}
        <pre><p class="info_message">{{ info_message }}</p></pre><br>
    {% endif %}
    {% if error_message %}
        <pre><p class="error_message">{{ error_message }}</p></pre><br>
    {% endif %}
    {% block content %}
    {% endblock %}
</div>

<div class="right"></div>

</body>
</>

templates/bid_saved.html
{% extends 'base.html' %}

{% block content %}
    <table class="auction_item">
        <tr>
            <td>
                Title
            </td>
            <td>
                {{ auction.title }}
            </td>
        </tr>
        <tr>
            <td>
                Seller
            </td>
            <td>
                {{ seller_name }}
            </td>
        </tr>
        <tr>
            <td>
                Item description
            </td>
            <td>
                {{ auction.description }}
            </td>
        </tr>
    </table>
{% endblock %}

templates/bidding_form.html
<script>
    function validateForm() {
        var input = document.getElementById("new_bid")
        bid = input.value;
        if (bid <= {{ auction.current_price }}) {
            alert("New bid must be higher than the current bid.");
            return false;
        }
        if (isNaN(bid)){
            alert("Please input a number.")
            return false;
        }
        if (bid.includes(".") && bid.split(".")[1].length > 2) {
            alert("Please use numbers with two decimal places or less.")
            return false;
        }
    }

    function updateCur(){
        var input = document.getElementById("new_bid")
        var output = document.getElementById("converted");
        output.innerHTML = (input.value * {{ rate }}).toFixed(2)
    }
</script>

{% if auction.active and not auction.banned %}
<form action="{% url 'auctionBid' auction.id %}" method="post" onsubmit="return validateForm()">
    {% csrf_token %}
    <input id="new_bid" name="new_bid" value="{{ auction.current_price }}" oninput="updateCur()" size="3" style="text-align: center; padding-right: 5px"/> EUR
    {% if currency != 'EUR' %}
    = <h id="converted">{{ starting_sum }} </h> {{ currency }}
    {% endif %}
    <input type="submit" name="action" value="Place bid">
</form><br>
{% endif %}

templates/confirm_auction.html
{% extends 'base.html' %}

{% block content %}
    Do you want to save this auction?<br><br>
    <form action="{% url 'auctionAdd' %}" method="POST">
        {% csrf_token %}
        {% include 'auction_table.html' %}
        <br>
        <input type="submit" name="confirmed" value="Yes">
        <input type="submit" name="confirmed" value="No">
    </form>
 {% endblock %}

templates/currency_picker.html
<form action="{% url 'change_currency' %}" method="POST" class="login" style="background-color: #6DDCBD; padding: 3px;border: black; border-style: dotted"">
    {% csrf_token %}
    View listings in:
    <select name="currency" id="currency" onchange="this.form.submit()">
        {% for code in request.session.currencies %}
            <option value="{{ code }}"
                {% if code == request.session.currency %}
                    selected
                {% endif %}>{{ code }}</option>
        {% endfor %}
    </select>
</form>

templates/edit_account.html
{% extends "base.html" %}

{% block content %}
    Current e-mail: {{ user.email }}<br>
    User has admin rights: {{ user.is_superuser }}<br><br>
    <form action="{% url 'edit_account' %}" method="POST">
        {% csrf_token %}
        <table border="0">
            {% for field in form.visible_fields %}
                <tr>
                    <td>{{ field.label_tag }}</td>
                    <td>{{ field }}</td>
                </tr>
            {% endfor %}
            <tr>
                <td colspan="2" align="center">
                    <input type="submit" value="Save changes" style="width: 100%">
                </td>
            </tr>
        </table>
    </form>
{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block content %}
    {% if user.is_authenticated %}
        Hello, {{ user }}!
    {% else %}
        Please log in
    {% endif %}
{% endblock %}

templates/login.html
{% if not user.is_authenticated %}
    <form action="{% url 'login' %}" method="POST" class="login">
        {% csrf_token %}
        <table>
            <tr>
                <td>
                    <input id="username" name="username" type="text", value="Username" /><br>
                    <input id="password" name="password" type="password", value="Password"/>
                </td>
                <td>
                    <button type="submit">Login</button>
                </td>
            </tr>
        </table>
    </form>
{% else %}
    <div class="login">
        <table border="0" class="text_white">
            <tr>
                <td>
                    Logged in: {{ user }}
                </td>
                <td rowspan="3">
                    <br><form action="{% url 'logout' %}" method="POST" style="padding-left: 10px">
                        {% csrf_token %}
                        <button type="submit">Log out</button>
                    </form>
                </td>
            </tr>
            <tr>
                <td>
                    <a href="{% url 'edit_account' %}" class="text_white">Edit account</a>
                </td>
            </tr>
        </table>
    </div>
{% endif %}

templates/navigation.html
<div class="navigation">
    <a href="{% url 'home' %}">Home</a><br>
    <a href="{% url 'auctions' %}">Browse auctions</a><br>
    {% if user.is_authenticated %}
        <a href="{% url 'auctionAdd' %}">Add auction item</a><br>
    {%  else %}
        <a href="{% url 'signup' %}">Register</a><br>
    {% endif %}
{% if user.is_superuser %}
    <a href="{%  url 'auctionListBanned' %}">List banned auctions</a><br>
    <a href="/admin/">Administrator panel</a><br>
{% endif %}
</div>

templates/search_bar.html
<div class="search">
    <form action="{% url 'search' %}" method="POST" class="search">
        {% csrf_token %}
        <input id="search" name="search" type="text" />
        <button type="submit">Search</button>
    </form>
</div>

templates/signup.html
{% extends "base.html" %}

{% block content %}
    <form action="{% url 'signup' %}" method="POST">
        {% csrf_token %}
        <table border="0">
            {% for field in signup_form.visible_fields %}
                <tr>
                    <td>{{ field.label_tag }}</td>
                    <td>{{ field }}</td>
                </tr>
            {% endfor %}
        <tr>
            <td colspan="2" align="center">
                <input type="submit" value="Register" style="width: 100%">
            </td>
        </tr>
        </table>
    </form>
{% endblock %}

templates/top.html
<div class="top">
    Top bar
    {% include 'search_bar.html' %}
    {% include 'login.html' %}
</div>